# Generated by Django 2.0.5 on 2018-09-02 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20180902_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='profile_pic',
            new_name='perfil_pic',
        ),
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='user',
            new_name='usuario',
        ),
    ]
