# Generated by Django 2.0.5 on 2018-08-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=264, unique=True)),
                ('nombre', models.CharField(max_length=264, unique=True)),
                ('tipo', models.CharField(max_length=264)),
                ('duracion', models.FloatField(blank=True, default=None, null=True, verbose_name='Duración')),
                ('duracion_unidad', models.CharField(blank=True, max_length=3, verbose_name='Unidad de duración')),
                ('zona', models.CharField(blank=True, max_length=10)),
                ('descripcion', models.CharField(max_length=5000, unique=True, verbose_name='Descripción')),
                ('comentarios', models.CharField(blank=True, max_length=5000, verbose_name='Comentarios')),
            ],
        ),
    ]
