# Generated by Django 2.0.5 on 2018-08-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='zona',
            field=models.CharField(blank=True, choices=[('Z1', '1'), ('Z2', '2'), ('Z3', '3'), ('Z4', '4'), ('Z5', '5')], max_length=10),
        ),
    ]
