# Generated by Django 2.0.5 on 2018-08-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0005_auto_20180825_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='actividad',
            field=models.CharField(choices=[('NT', 'Natación'), ('CL', 'Ciclismo'), ('AT', 'Atletismo'), ('FZ', 'Fuerza'), ('DS', 'Descanso'), ('CD', 'Otra-Cardio')], max_length=264),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='descripcion',
            field=models.CharField(max_length=5000, verbose_name='Descripción'),
        ),
    ]
