# Generated by Django 2.0.5 on 2018-08-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0006_auto_20180825_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='duracion',
            field=models.FloatField(default=None, null=True, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='duracion_unidad',
            field=models.CharField(choices=[('min', 'min'), ('hr', 'hr'), ('m', 'm'), ('km', 'km')], max_length=3, verbose_name='Unidad de duración'),
        ),
    ]
