# Generated by Django 2.0.5 on 2018-08-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0008_auto_20180828_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='periodo',
            field=models.CharField(blank=True, choices=[('BA', 'Base'), ('PR', 'Progresión'), ('CE', 'Cenít'), ('CO', 'Competencia'), ('TO', 'Todos')], max_length=10),
        ),
    ]
