# Generated by Django 2.0.5 on 2018-08-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0009_auto_20180828_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='periodo',
            field=models.CharField(blank=True, choices=[('TO0', 'Todos'), ('BA0', 'Base'), ('PR0', 'Progresión'), ('ZE0', 'Zenít'), ('CO0', 'Competencia'), ('BP0', 'Base, Progresión'), ('BZ0', 'Base, Zenít'), ('BC0', 'Base, Competencia'), ('PZ0', 'Progresión, Zenít'), ('PC0', 'Progresión, Competencia'), ('ZC0', 'Zenít, Competencia'), ('BPZ', 'Base, Progresión, Zenít'), ('BPC', 'Base, Progresión, Competencia'), ('BZC', 'Base, Zenít, Competencia'), ('PZC', 'Progresión, Zenít, Competencia')], max_length=10),
        ),
    ]
